

export const noticias = [
    {
      id:1,
      title: 'Lanzan un segundo llamado a licitación para la construcción del Centro de Salud N°2',
      content: 'Después de la presentación de una oferta por más del doble del presupuesto oficial, el gobierno municipal lanzó un segundo llamado a oferentes como parte de la licitación que apunta a construir la nueva sede del Centro de Atención Primaria de la Salud (CAPS) N°2.',
      category: ['Politica','home'],
      content2:' Lanzan un segundo llamado a licitación para la construcción del Centro de Salud N°2.Fue resuelto por el gobierno municipal tras la presentación de una oferta que duplicó el presupuesto oficial.Después de la presentación de una oferta por más del doble del presupuesto oficial, el gobierno municipal lanzó un segundo llamado a oferentes como parte de la licitación que apunta a construir la nueva sede del Centro de Atención Primaria de la Salud (CAPS) N°2.A siete años del traslado “provisorio” del centro de salud a una sede gremial ubicada en 12 de Octubre 4445, la construcción de su nueva instalación todavía sigue pendiente de ser licitada y para eso el gobierno municipal formalizó en las últimas horas un segundo llamado a licitación cuya apertura de sobres, para conocer las propuestas presentadas, quedó programada para el 24 de mayo.El segundo llamado fue convocado por el gobierno después de la apertura de sobres y evaluación de dos ofertas presentadas en el primero: una fue rechazada por no cumplir con algunos requisitos y la otra fue evaluada pero contenía un monto de más del doble del proyectado.'
    },
    {
      id:2,
      title: 'Sin mayores avances con el nuevo DT, Osvaldo Nartallo volverá a dirigir a Alvarado',
      content: 'Desde que el entrenador César Vigevani dejó su puesto tras un mal arranque de campeonato, en el predio de Alvarado los teléfonos de los dirigentes están ocupados con el objetivo de encontrar a su reemplazante, aunque en el club confirmaron que se tomarán el tiempo necesario para elegir a la persona indicada que pueda enderezar el rumbo. Ante este panorama, desde la institución marplatense aseguraron que el interinato de Osvaldo Nartallo se estirará hasta por lo menos el partido del próximo domingo ante Almagro.“Todavía no hay nada concreto y además no hay un tiempo estipulado para cerrar con el nuevo entrenador”, confirmaron desde el Torito a Qué digital y luego ratificaron que Osvaldo Nartallo también será quien dirija al plantel profesional el próximo encuentro.',
      category: 'Deportes',
      content2:'Desde que el entrenador César Vigevani dejó su puesto tras un mal arranque de campeonato, en el predio de Alvarado los teléfonos de los dirigentes están ocupados con el objetivo de encontrar a su reemplazante, aunque en el club confirmaron que se tomarán el tiempo necesario para elegir a la persona indicada que pueda enderezar el rumbo. Ante este panorama, desde la institución marplatense aseguraron que el interinato de Osvaldo Nartallo se estirará hasta por lo menos el partido del próximo domingo ante Almagro.“Todavía no hay nada concreto y además no hay un tiempo estipulado para cerrar con el nuevo entrenador”, confirmaron desde el Torito a Qué digital y luego ratificaron que Osvaldo Nartallo también será quien dirija al plantel profesional el próximo encuentro.Nartallo, al igual que cuando se fueron Walter Gastón Coyette y Manuel Fernández, dirigió de forma interina a Alvarado ante San Telmo en un partido que terminó con sabor amargo ya que el Candombero logró empatar el juego 1 a 1 en la última pelota del partido. El triunfo como visitante hubiese significado un envión anímico muy importante y además el primero fuera de Mar del Plata en lo que va de la temporada, pero Erik Bodencer de cabeza le amargó la ilusión y regresó a la ciudad con solo un punto.Ahora, el DT de Alvarado en la Liga Marplatense de Fútbol tendrá una semana completa de trabajo junto al ayudante Ezequiel Trapito Ceballos de cara al próximo encuentro, a disputarse el domingo desde las 16.30 ante Almagro en el estadio José María Minella por la fecha 16 de la Zona A de la Primera Nacional.Para este compromiso, Osvaldo Nartallo tendrá varias bajas de peso ya que no podrá contar con Guido Vadalá que alcanzó la quinta amarilla, mientras que Franco Bellocq aún debe una fecha debido a que cuando lo expulsaron ante Temperley le dieron dos jornadas de suspensión, y tanto Julián Vitale como Sebastián Ramírez continúan lesionados y no llegarán al próximo compromiso. Asimismo, la buena noticia es que recuperará a Alan Robledo, quien ya cumplió la fecha de suspensión.Tras haberse disputado las primeras 15 fechas, Alvarado se ubica en el puesto 17 de la Zona A con 15 puntos, solamente por encima de San Telmo (12) y All Boys (14), aunque además se encuentra a 4 unidades de los puestos de Reducido en busca del segundo ascenso que otorga la Primera Nacional a la Liga Profesional.'
    },
    {
      id:3,
      title: 'Desempleo: qué puestos pueden desaparecer por la tecnología y cuándo va a pasar',
      content: 'En las anteriores revoluciones industriales, la automatización también se encargó de barrer con diferentes tareas que realizaban los humanos. Al principio, las máquinas sustituían las tareas repetitivas y manuales. En ese entonces, las tareas tanto cognitivas como manuales estaban al alcance de la automatización siempre que fuesen repetitivas. Ahora, a medida que desarrollos como la IA se hace cada vez más potentes y los robots más hábiles, las tareas cognitivas y manuales no repetitivas se hacen cada vez más automatizables.Hay varios casos de esta automatización de nueva ola: la investigación de casos que realizan los asistentes jurídicos, el uso del reconocimiento facial junto a las cámaras automatizan parte del trabajo de seguridad, el desarrollo de vehículos autónomos, que impacta en los empleos de los conductores de camiones, o el desarrollo de la escritura creativa con asistentes virtuales como ChatGPT. El avance de la nueva ola de automatización sobre las habilidades otrora territorio sagrado de los humanos pone en jaque la falacia ludita que se mantuvo en anteriores revoluciones industriales: los puestos de trabajo que se pierdan en un determinado ámbito económico se crearán en otro. Por ejemplo, el 90% de los empleos de la economía estadounidense se encuentran en el sector servicios, donde la nueva automatización puede crear enormes olas de desempleo.',
      category: 'Tecnologia',
      content2:'No es la primera vez que se lee que un nuevo cambio tecnológico va a traer desempleo. La llegada de ChatGPT, el modelo de procesamiento de lenguaje natural, es simplemente un capítulo más como lo fue en su momento la computadora personal, la línea de ensamblaje o el automóvil. Es, así, sencillo tanto declarar la nueva era de los soberanos robóticos como desestimar el impacto de la nueva ola de automatización. Que no empezó -ni terminará- con ChatGPT. Pero la realidad suele ser más compleja. La nueva ola de automatización incluye no solo estos modelos de procesamiento del lenguaje natural (o "chatbots") sino desarrollos que hoy no están tan de moda como Baxter, el robot multitasking que llegó a reemplazar a los ya anticuados brazos robóticos que todos vimos en las fábricas de autos durante las últimas décadas.Baxter revolucionó el sector de la robótica industrial por su flexibilidad y su capacidad de aprendizaje y rápida reutilización para tareas nuevas (algo que le permite no ser una pieza obsoleta de capital cuando la línea de ensamble donde hoy operan los brazos robóticos dejan de funcionar. Estos robots sirven pura y exclusivamente para esa tarea mientras que Baxter es reprogramable). De la misma manera, las supercomputadoras de cálculo están realizando trabajos de investigación científica tal como lo hace el robot científico Adam. Mientras investigaba la genómica funcional basada en la levadura, Adam se convirtió en la primera máquina de la historia que ha descubierto nuevos conocimientos científicos independientemente de sus creadores humanos.Algo cambió. En las anteriores revoluciones industriales, la automatización también se encargó de barrer con diferentes tareas que realizaban los humanos. Al principio, las máquinas sustituían las tareas repetitivas y manuales. En ese entonces, las tareas tanto cognitivas como manuales estaban al alcance de la automatización siempre que fuesen repetitivas. Ahora, a medida que desarrollos como la IA se hace cada vez más potentes y los robots más hábiles, las tareas cognitivas y manuales no repetitivas se hacen cada vez más automatizables.Hay varios casos de esta automatización de nueva ola: la investigación de casos que realizan los asistentes jurídicos, el uso del reconocimiento facial junto a las cámaras automatizan parte del trabajo de seguridad, el desarrollo de vehículos autónomos, que impacta en los empleos de los conductores de camiones, o el desarrollo de la escritura creativa con asistentes virtuales como ChatGPT. El avance de la nueva ola de automatización sobre las habilidades otrora territorio sagrado de los humanos pone en jaque la falacia ludita que se mantuvo en anteriores revoluciones industriales: los puestos de trabajo que se pierdan en un determinado ámbito económico se crearán en otro. Por ejemplo, el 90% de los empleos de la economía estadounidense se encuentran en el sector servicios, donde la nueva automatización puede crear enormes olas de desempleo.'
    },
    {
      id:4,
      title: 'El ciclo De Plaza en Plaza se prepara para los 150 años de Mar del Plata',
      content: 'Este mes continúa el ciclo De Plaza en Plaza con el objetivo de ofrecer una variedad de espectáculos en diferentes puntos de la ciudad con entrada libre y gratuita. El Municipio a través de la Secretaría de Cultura acerca propuestas los fines de semana entre las 15 y las 17. En esta oportunidad, decidieron sumar actividades para conmemorar los 150 años de Mar del Plata que se cumplen el próximo 10 de febrero y un espectáculo para generar conciencia previo al feriado del 25 de mayo.',
      category: 'Cultura',
      content2:'Este mes continúa el ciclo De Plaza en Plaza con el objetivo de ofrecer una variedad de espectáculos en diferentes puntos de la ciudad con entrada libre y gratuita. El Municipio a través de la Secretaría de Cultura acerca propuestas los fines de semana entre las 15 y las 17. En esta oportunidad, decidieron sumar actividades para conmemorar los 150 años de Mar del Plata que se cumplen el próximo 10 de febrero y un espectáculo para generar conciencia previo al feriado del 25 de mayo.Como todos los meses, la Secretaría de Cultura dio a conocer la programación de los espectáculos que se realizarán a lo largo de mayo en el ciclo De Plaza en Plaza. A su vez, informaron que se llevará a cabo “150 formas de CelebrARTE MDP”, con actividades en torno al 150 aniversario de la fundación de la ciudad -que se estableció en 1874- que se cumplirá el próximo 10 de febrero. “Incorporamos al ciclo De Plaza en Plaza presentaciones en ONG, sociedades de fomento y asociaciones civiles”, indicaron desde el organismo municipal. De esta manera este sábado a las 17 en la Federación Italiana, ubicada en La Roja 2043, se podrá disfrutar de la música del Cuarteto Vivaldi y del humor de Beto Mena. En tanto que el sábado 13 de mayo a las 16 en Casa Balear, 20 de Septiembre 1975, se realizará un espectáculo de tango con Rocío Baraglia y la compañía Confluir con una performance especial dirigida por Jésica Arias.Para el domingo 21 a las 16 en Castilla y León, ubicado en Hipólito Yrigoyen 2067, se presentará el cantautor de folklore conocido como el Pulpo Ponce y la agrupación folclórica Luna Cautiva. Además, tendrá lugar el “Festival P3rla” el miércoles 24 y jueves 25 de mayo, aunque aún no confirmaron dónde se realizará el evento que tiene como objetivo difundir emprendimientos que apunten a la sostenibilidad y se podrá disfrutar de una función con entrada libre y gratuita.Finalmente, el sábado 27 de mayo en La Casa de Italia, ubicada en Edison 127, se podrá disfrutar de “Pago Argentino”, un grupo musical marplatense que interpreta clásicos del folklore.'
    },
    {
      id:5,
      title: 'Autorizan subas mensuales de hasta 4,5% en telefonía, TV e Internet hasta diciembre',
      content: 'El Ente Nacional de Comunicaciones autorizó a las empresas de telefonía, televisión por cable o satelital e Internet a implementar aumentos mensuales en sus tarifas de hasta un 4,5% hasta fin de año y tomando como referencia los valores del mes previo.Según la Resolución 557/2023 del Enacom -firmada por su director, Claudio Ambrosini- dada a conocer este martes en el Boletín Oficial, fue autorizado en primer lugar un aumento retroactivo al 1 de mayo en los precios minoristas de cualquiera de los planes en la modalidad pospaga y/o mixta, tomando como referencia los precios vigentes al 30 de abril.',
      category: ['Politica','home'],
      content2:'El Gobierno autorizó este martes aumentos mensuales hasta fin de año en televisión paga, telefonía e internet. Las licenciatarias podrán aplicar sucesivos incrementos de hasta un 4,5% desde mayo hasta diciembre de 2023. La medida fue tomada por el Ente Nacional de Comunicaciones y publicada en el Boletín Oficial a través de la Resolución 557/2023. Lleva la firma del presidente de Enacom, Claudio Ambrosini."Sin desatender el diálogo con el sector, advirtiendo que el último incremento autorizado por este ENACOM fue de aplicación sucesiva y mensual en el período comprendido entre enero y abril de 2023; corresponde autorizar nuevos incrementos con similar aplicación a partir de mayo y hasta diciembre de 2023, evaluados en el contexto económico y dificultades que se atraviesan para todos los actores involucrados, prestadoras y público usuario", reza el texto. "Siguiendo ese temperamento, los requerimientos de nuevos aumentos se fundamentan a partir de los mayores costos y el impacto de las oscilaciones de las principales variables económicas en la operatoria de las Licenciatarias durante los meses transcurridos desde el inicio de la reglamentación de precios minoristas", sumaron. '
    },
    {
      id:6,
      title: 'Comenzó el Panamericano de taekwondo ITF en Mar del Plata',
      content: 'A lo largo de cuatro extensos días de actividad deportiva, el Polideportivo Islas Malvinas de Mar del Plata es escenario del Campeonato Panamericano de taekwondo ITF que comenzó por la mañana de este miércoles y se extenderá hasta el sábado 13 de mayo. La entrada para presenciar el evento es libre y gratuita en todas las jornadas, que tendrán como horario de inicio a las 10 a diferencia del sábado, día que finaliza el torneo y cuando comenzará la acción desde las 9.En este importante evento deportivo competirán alrededor de 1800 taekwondistas de 14 diferentes países de América y que en esta oportunidad, en su edición decimoquinta, por primera vez contará con la presencia de atletas de Europa, más precisamente provenientes de Italia. Además, el certamen que durará cuatro días tendrá la participación de 70 jueces internaciones, y de un público estimado de 5000 espectadores a lo largo de la actividad deportiva diaria.',
      category: ['Deportes','home'],
      content2:`

      A lo largo de cuatro extensos días de actividad deportiva, el Polideportivo Islas Malvinas de Mar del Plata es escenario del Campeonato Panamericano de taekwondo ITF que comenzó por la mañana de este miércoles y se extenderá hasta el sábado 13 de mayo. La entrada para presenciar el evento es libre y gratuita en todas las jornadas, que tendrán como horario de inicio a las 10 a diferencia del sábado, día que finaliza el torneo y cuando comenzará la acción desde las 9.
      
      En este importante evento deportivo competirán alrededor de 1800 taekwondistas de 14 diferentes países de América y que en esta oportunidad, en su edición decimoquinta, por primera vez contará con la presencia de atletas de Europa, más precisamente provenientes de Italia. Además, el certamen que durará cuatro días tendrá la participación de 70 jueces internaciones, y de un público estimado de 5000 espectadores a lo largo de la actividad deportiva diaria.
      
          Cabe mencionar que existen dos estilos de taekwondo, el WTF, que es el que se encuentra entre los deportes olímpicos, y el ITF, que es el que se desarrollará en Mar del Plata en este campeonato internacional, estilo más tradicional y más cerca del arte marcial en sí, con mucho más defensa personal y técnica.
      
      Ante esto, en la competencia de taekwondo que se lleva a cabo en Mar del Plata hay disciplinas de formas, lucha, lucha preestablecida, roturas de poder y habilidad y competencias por equipos en forma y lucha. Además, este Campeonato Panamericano de taekwondo ITF tiene como novedad la incorporación de la categoría Maestros, donde se enfrentarán quienes tengan cinturón de VII Dan en adelante.
      
      Es así que la actividad comenzó este miércoles desde las 10 y para el viernes al mismo horario está programada la gala donde todas las categorías tendrán su final como evento principal y donde se entregará el cinturón de campeón Panamericano, premio que se otorga por primera vez en este evento. Asimismo, el sábado a las 9 se realizarán las competencias de los equipos nacionales, donde participarán las selecciones de todos los países presentes.
      `
    },
    {
      id:7,
      title: 'Tecnología: cómo será el 6G y sus diferencias con las generaciones anteriores',
      content: 'Se espera el 6g tenga velocidades de transmisión de datos en el rango de un terabit por segundo, latencias de 0,1 milisegundos, soporte de conectividad para vehículos con velocidades hasta 1000 km/h y niveles de fiabilidad del 99,99999 %.Los especialistas confían en que esto posibilitará múltiples aplicaciones: sistemas de control en tiempo real de robots, conectividad masiva de todo tipo de dispositivos (electrodomésticos, mobiliario urbano, wearables, bicicletas), hasta 107 dispositivos por kilómetro cuadrado y la implementación de entornos de realidad mixta y realidad extendida, con aplicaciones tan espectaculares como las comunicaciones holográficas.',
      category: ['Tecnologia','home'],
      content2:`Cuando ni siquiera había comenzado a desplegarse el 5G, China ya empezó a hablar del 6G y de sus intenciones de tenerlo preparado para finales de la presente década. Corea del Sur fue más allá asegurando que llevaría a cabo el primer proyecto piloto 6G en 2026 y Huawei prometió poner pronto en órbita dos satélites para comenzar con las pruebas preliminares del 6G.

      Pero, ¿qué es realmente el 6G? ¿Qué ventajas aportará sobre ese 5G que se está desplegando poco a poco? ¿Cuándo se conectarán nuestros móviles a la sexta generación de redes? A continuación, recopilamos todo lo que se sabe hasta ahora del 6G para ir actualizando el artículo a medida que salgan más datos de esta ¿futura? tecnología.
      ¿Qué es el 6G?
      6G
      
      El 6G, como su nombre indica, es la sexta generación de la conectividad móvil. Del mismo modo que el 4G sucedió al 3G y el 5G al 4G, el 6G llegará para reemplazar el 5G con una mayor velocidad y una latencia aún menor. Antes, eso sí, pasaremos por un estado intermedio conocido como 5G+ o 5G avanzado, que irrumpirá en el mercado en 2024. Huawei lo llama 5.5G y asegura que, gracias a la tecnología MIMO, alcanzará velocidades de 10 Gbps.
      Del 1G al 5G: así funcionan las redes móviles y todo lo que cambia tras cada salto de generación
      En Xataka Móvil
      Del 1G al 5G: así funcionan las redes móviles y todo lo que cambia tras cada salto de generación
      
      Al igual que el 5G, uno de los objetivos del 6G es reducir aún más la latencia en las conexiones y aumentar notablemente la velocidad de transmisión. Aún no se ha definido el estándar del 6G y se desconocen las bandas de espectro que se utilizarán para la transmisión de datos, pero se estima que su comercialización será en 2030 y que los primeros casos de uso reales en esta red podrían llegar entre 2026 y 2028.  `
    },
    {
      id:8,
      title: 'La sed se estrena en Mar del Plata: “Me parecía interesante echar luz sobre esta adicción”',
      content: 'El documental “La sed”, de Matías Scarvaci, se estrena esta semana en Mar del Plata con la narración del proceso que atraviesa una persona en instancias de recuperación ante el consumo problemático del alcohol. “La película sirvió para articular escenas que en la vida todavía no habían sucedido. En ese sentido, fue muy poderoso y muy revelador”, destacó el cineasta previo a las funciones en Mar del Plata.Para el cineasta, el primer impulso para filmar “La sed” fue producto de una amistad. “Tengo un amigo, actor, colega y sabía de su adicción al alcohol, fui testigo de su carrera alcohólica y a partir de ese vínculo surgió la idea de hacer un documental sobre el tema”, compartió para Qué digital Matias Scarvaci.“Luego otro amigo me presentó a Charly, se conocían de la infancia. Nos contactamos y lo fui a visitar a Mar del Plata, tomamos un café mientras yo estaba participando con otra película del Festival Internacional de Cine. Él fue muy generoso en abrir su historia, su corazón y brindarse para hacer la película“, agregó.',
     category: ['Cultura','home'],
content2:`El documental “La sed”, de Matías Scarvaci, se estrena esta semana en Mar del Plata con la narración del proceso que atraviesa una persona en instancias de recuperación ante el consumo problemático del alcohol. “La película sirvió para articular escenas que en la vida todavía no habían sucedido. En ese sentido, fue muy poderoso y muy revelador”, destacó el cineasta previo a las funciones en Mar del Plata.

“La sed” se podrá ver este martes y miércoles a las 19 en Espacio Incaa Chauvin, San Luis 2849. Las entradas a $200 se pueden adquirir directamente en la boletería del complejo. Según informaron, Juan Carlos Carrere, “Charly”, en recuperación por el consumo problemático del alcohol, y Montserrat Catasus Blanch, que dirige una ONG que se ocupa de la asistencia, compartirán una charla abierta con el público en la primera jornada.

El protagonista vive con su esposa en Mar del Plata, y por su grave problema con el alcohol realizó un tratamiento en la comunidad terapéutica Posada del Inti y ahora continúa una vez por semana concurriendo a Alcohólicos Anónimos. “La película viene teniendo críticas brillantes porque Matías (Scarvaci) es un groso. Supo cómo contar la vida de Charly Carrere donde años de consumo, dolor y tristeza quedan reflejados en este documental. Pero lo más importante es cómo se puede modificar esta realidad, se puede hacer algo diferente”, dijo el titular de la comunidad terapéutica, Fabián Messina.

Para el cineasta, el primer impulso para filmar “La sed” fue producto de una amistad. “Tengo un amigo, actor, colega y sabía de su adicción al alcohol, fui testigo de su carrera alcohólica y a partir de ese vínculo surgió la idea de hacer un documental sobre el tema”, compartió para Qué digital Matias Scarvaci.

“Luego otro amigo me presentó a Charly, se conocían de la infancia. Nos contactamos y lo fui a visitar a Mar del Plata, tomamos un café mientras yo estaba participando con otra película del Festival Internacional de Cine. Él fue muy generoso en abrir su historia, su corazón y brindarse para hacer la película“, agregó.

Como protagonista del documental, tanto Charly, su pareja y amigos cuentan en detalle cómo era su vida en el momento más crítico de la enfermedad, y la cámara lo acompaña sin prejuicios para narrar cómo es su presente.

Lejos del sensacionalismo, la película busca reflejar cómo fue el pasado de una persona afectada por su consumo de alcohol y cuál es su presente. “El tema me parece muy poderoso y muy digno de contar, con multiplicidad de sentidos, situación de ocultamiento en general. Me parece que aún hay mucho tabú sobre el tema y me parecía interesante echar luz sobre esta adicción de la cual no se habla mucho. Es tan común y atraviesa por todos lados a la sociedad que me resultó interesante poner la mirada en ese asunto”, indicó.

Para lograr un resultado directo, el realizador sostuvo que “durante la filmación el acercamiento fue paulatino para establecer confianza, tanto con Charly como con el resto de los personajes”. “Un acercamiento sin moralizar, sin bajar línea, sin establecer una división sobre lo que está bien y lo que está mal, sino simplemente acercarnos a ese universo y de esa manera poder desplegar la problemática“, compartió.

En este sentido, el cineasta remarcó que el proceso fue muy interesante. “Sobre todo con Charly porque a medida que avanzamos en el rodaje aparecieron situaciones que estaban ocultas o que nunca se habían dicho. Eso fue muy fuerte, muy duro, tanto para el protagonista, su entorno como para mí y para el equipo. Fueron jornadas muy difíciles”, recordó.`
    },
    


  ];
  export default noticias;